development:
  cloud_name: pollen-image-store
  api_key: ENV['API_KEY']
  api_secret: ENV['API_SECRET']
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: pollen-image-store
  api_key: ENV['API_KEY']
  api_secret: ENV['API_SECRET']
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: pollen-image-store
  api_key: ENV['API_KEY']
  api_secret: ENV['API_SECRET']
  enhance_image_tag: true
  static_image_support: false
